version: '3'
services:
  db:
    image: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

